export const projects = [
  {
    title: "Animal Hospital Website",
    description:
      "This is a website for a vetinary clinic that specialize in cats",
    image: "/images/cat-vet.jpg",
    tags: ["NextJs", "Styled Components", "SwiperJS", "NodeJs"],
    source: "https://babajide-omar-animal-hospital.netlify.app/",
    visit: "#",
    id: 0,
  },
  {
    title: "Project Explorer API",
    description:
      "The backend of the Project Explorer project, repository for final year students to submit projects and search projects submitted by others to learn from. Students can signup or login via the regular signup/login procedures, or do so via Facebook or Google.",
    image: "/images/explorer-backend.jpg",
    tags: ["MongoDB", "Express", "Passport", "Node"],
    source: "https://jide-explorer.herokuapp.com",
    visit: "https://github.com/Babajide777/project-explorer",
    id: 1,
  },
  {
    title: "Project Explorer Client",
    description:
      "The frontend of the Project Explorer project, a repository for final year students to submit projects and search projects submitted by others to learn from. Students can signup or login via the regular signup/login procedures, or do so via Facebook or Google.",
    image: "/images/explorer.jpg",
    tags: ["React", "Node", "Bootstrap", "React-Bootstrap"],
    source: "https://babajide-project-explorer.netlify.app",
    visit: "https://github.com/Babajide777/project-explorer-client",
    id: 2,
  },
  {
    title: "King Jesus E-Commerce",
    description:
      "This is a fully functional ECommerce website with cart, payment, search, emailing, and Admin section all working properly. The Repo is private as the application is for a client.",
    image: "/images/kingJesus.PNG",
    tags: ["JavaScript", "MongoDB", "Express", "Node", "Flutterwave"],
    source: "https://kingjesus-ecommerce.herokuapp.com/",
    visit: "#",
    id: 3,
  },
  {
    title: "King Jesus E-Commerce Admin",
    description: "Admin Section for king Jesus E-Commerce website",
    image: "/images/king-admin.jpg",
    tags: ["JavaScript", "MongoDB", "Express", "Node", "Flutterwave"],
    source: "https://kingjesus-ecommerce.herokuapp.com/admin",
    visit: "#",
    id: 4,
  },
  {
    title: "Eventis",
    description: "Landing page for an upcoming video sharing website",
    image: "/images/eventis.jpg",
    tags: ["CSS3", "HTML5"],
    source: "https://www.eventis.me/",
    visit: "#",
    id: 5,
  },
  {
    title: "Ever Tech",
    description:
      "I was part of the team that built the Ever Tech website from scratch",
    image: "/images/ever-tech.png",
    tags: ["NextJs", "TypeScript", "ChakraUI", "StyledComponents"],
    source: "https://services.ever.co/",
    visit: "#",
    id: 6,
  },
  {
    title: "Ever Website",
    description: "I was part of the team that built the Ever website",
    image: "/images/ever.png",
    tags: ["NextJs", "TypeScript", "ChakraUI", "StyledComponents"],
    source: "https://ever.co/",
    visit: "#",
    id: 7,
  },
  {
    title: "Tae lolu Website",
    description: "I built this fullstack app for an import-export company",
    image: "/images/tae-lolu.jpg",
    tags: ["NextJs", "TypeScript", "nodemailer", "StyledComponents"],
    source: "https://www.taelolu.com/",
    visit: "#",
    id: 8,
  },
  {
    title: "Togao Consults Website",
    description:
      "I built this fullstack app for an insurance consultancy company",
    image: "/images/togao.png",
    tags: ["NextJs", "TypeScript", "tailwindCSS"],
    source: "https://www.togaoconsults.com/",
    visit: "#",
    id: 9,
  },
  {
    title: "Assured Aim FX Web App",
    description: "I built this fullstack app for a forex company",
    image: "/images/assured.png",
    tags: [
      "NextJs",
      "ExpressJS",
      "NodeJS",
      "ReduxToolkit",
      "MongoDB",
      "StyledComponents",
    ],
    source: "https://www.assuredaimforex.com/",
    visit: "#",
    id: 10,
  },
];

export const TimeLineData = [
  { year: 2019, text: "Started my Web development journey" },
  { year: 2021, text: "Completed EdConnect bootcamp" },
  {
    year: 2021,
    text: "Worked as a freelance fullstack developer at codementor and Upwork",
  },
  { year: 2021, text: "Worked with Eventis as a Backend Engineer" },
  { year: 2022, text: "Worked with Ever as a Frontend Web Developer" },
];
